## Service definition ##
application:
  schemaVersion: 0.0.1
  name: ServiceFabricMeshApp
  services:
    - name: ToDoService
      description: ToDoService description.
      osType: Windows
      codePackages:
        - name: ToDoService
          image: todoservice:dev
          endpoints:
            - name: ToDoServiceListener
              port: 20001
          environmentVariables:
            - name: ASPNETCORE_URLS
              value: http://+:20001
#            - name: ApplicationInsights:InstrumentationKey
#              value: "<Place AppInsights key here, or reference it via a secret>"
          resources:
            requests:
              cpu: 0.5
              memoryInGB: 1
      replicaCount: 1
      networkRefs:
        - name: ServiceFabricMeshAppNetwork