version: '3.0'

services:
  votingweb:
    image: votingweb:1.0-linux
    environment:
      "ASPNETCORE_URLS": http://+:8080
      "Voting_BackendHostName": votingdata
      "Voting_BackendHostPort": 8288
    ports:
      - "8080:8080"

  votingdata:
    image: votingdata:1.0-linux
    environment:
      "ASPNETCORE_URLS": http://+:8288
    ports:
      - "8288:8288"
    