## Service definition ##
application:
  schemaVersion: 0.0.1
  name: ServiceFabricMeshApp
  services:
    - name: WebFrontEnd
      description: WebFrontEnd description.
      osType: Windows
      codePackages:
        - name: WebFrontEnd
          image: webfrontend:dev
          endpoints:
            - name: WebFrontEndListener
              port: 20002
          environmentVariables:
            - name: ASPNETCORE_URLS
              value: http://+:20002
#            - name: ApplicationInsights:InstrumentationKey
#              value: "<Place AppInsights key here, or reference it via a secret>"
            - name: AppName
              value: ServiceFabricMeshApp
            - name: ApiHostPort
              value: 20001
            - name: ServiceName
              value: ToDoService
          resources:
            requests:
              cpu: 0.5
              memoryInGB: 1
      replicaCount: 1
      networkRefs:
        - name: ServiceFabricMeshAppNetwork