application:
  schemaVersion: 1.0.0-preview1
  name: Fireworks
  properties:
    description: A sample application that shows multiple types of micro-services. It has a web frontend that displays the fireworks based on the type of the worker services.
    services:
      - name: blue
        properties:
          description: Fireworks blue worker container. This container sends a ping message to the web service that counts the worker containers.
          osType: Windows
          codePackages:
            - name: worker
              image: azure-mesh-fireworks-worker:dev-v1
              environmentVariables:
                - name: OBJECT_TYPE
                  value: blue
                - name: OBJECT_COUNTER_ADDRESS
                  value: web:8080
              resources:
                requests:
                  cpu: 0.25
                  memoryInGB: 0.5
          replicaCount: 1
          networkRefs:
            - name: FireworksNetwork
      - name: green
        properties:
          description: Fireworks green worker container. This container sends a ping message to the web service that counts the worker containers.
          osType: Windows
          codePackages:
            - name: worker
              image: azure-mesh-fireworks-worker:dev-v1
              environmentVariables:
                - name: OBJECT_TYPE
                  value: green
                - name: OBJECT_COUNTER_ADDRESS
                  value: web:8080
              resources:
                requests:
                  cpu: 0.25
                  memoryInGB: 0.5
          replicaCount: 1
          networkRefs:
            - name: FireworksNetwork