FROM microsoft/aspnetcore:2.0.6-nanoserver-sac2016 AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/aspnetcore-build:2.0.6-2.1.101-nanoserver-sac2016 AS build
WORKDIR /src
COPY ServiceFabricSBZVoting.sln ./
COPY ServiceFabricSBZVoting/ServiceFabricSBZVotingWeb.csproj ServiceFabricSBZVoting/
RUN dotnet restore -nowarn:msb3202,nu1503
COPY . .
WORKDIR /src/ServiceFabricSBZVoting
RUN dotnet build -c Release -o /app

FROM build AS publish
RUN dotnet publish -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "ServiceFabricSBZVotingWeb.dll"]
